### ISSUE TITLE
Question: why is shortcut-fe still needed when there is already offload support in trunk?

### ISSUE THREAD

**Issue by MOZGIII** [juppin/openwrt_custom_builds_trunk#1]
Why is shortcut-fe still needed when there is already offload support in trunk?
I'm not an expert, and I'm interested in understanding why're you still using it.

**Comment by juppin** [comment]
The flow offload package is from kernel version 4.16 backported to 4.14 by a great openwrt dev, but platform ar71xx is only on kernel 4.9 and therefore no flow offload for ar71 devices...
ar71 will never be updated to 4.14, so we need shortcut-fe for this devices if we want offload connections.

**Comment by MOZGIII** [comment]
Oh...
Thanks for explanation.
I was hoping to get 4.14 on my Archer C7 v2 soon, but turns out it's not going to happen...
Do you have a link with more info on that?

**Comment by juppin** [comment]
https://forum.lede-project.org/t/is-anybody-working-on-linux-4-14-for-ar71xx-platform-porting-guide/13013

**Comment by MOZGIII** [comment]
Thanks a lot!
