### ISSUE TITLE
Kmod-fs-ext4 is not included

### ISSUE THREAD

**Issue by jgvega** [juppin/openwrt_custom_builds_trunk#2]
Hi Juppin.
Fast path works fine.

But i can't mount my hdd partition because are ext3 and ext4.
Your image for wrd3600 haven't kmod-fs-ext4.
Regards.

**Comment by juppin** [comment]
Added build with ext4 and e2fsprogs..

https://github.com/juppin/openwrt_custom_builds_trunk/tree/master/ar71xx_8mb_luci-ssl_nano_ddns_sqm_sfe_openvpn_wpad_openssl_dnsmasq-full_extroot-f2fs-ext4

**Comment by jgvega** [comment]
All rigth now!!
Fast path works fine and extroot has installed with minidlna, samba, transmission, ftp.
More speed. It's Incredible!
Juppin are great.
Thanks.
