### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by brick2008** [juppin/openwrt_custom_builds_trunk#3]
mips fpu emulator is enable？
when I use opkg install ,the device is hang,can not ping.   (4310v1)
suggest add ppp-mod-pppoe.
sorry for my english :)

**Comment by juppin** [comment]
> mips fpu emulator is enable？

is not enabled... did you need it?

> suggest add ppp-mod-pppoe

should be included in image

which packet do you want to install? happens this on all packages...
did you have a log?

**Comment by brick2008** [comment]
mips fpu emulator is useful, eg. kcptun with golang
yes,all packages.
like this:
opkg install xxx
downloading.......................
config.......................
It's crashed,no response.and after reboot I can not find the log.

**Comment by juppin** [comment]
As i know "mips fpu emulator" did decrease performance drastically....
Would be better to compile all binaries with soft fpu...
Serial log would be great for your problem with opkg... Are you able to provide one?

**Comment by brick2008** [comment]
well,I have already done this.
I'm using gwlim's rom now,regrettably.
